### ISSUE TITLE
Socket joining undefined topic

### ISSUE THREAD

**Issue by Dkendal** [StemboltHQ/battle_snake#5]
```
[info] Replied board_viewer:undefined :ok
[info] JOIN game_admin:undefined to BattleSnake.GameAdminChannel
  Transport:  Phoenix.Transports.WebSocket
  Parameters: %{}
[error] an exception was raised:
    ** (MatchError) no match of right hand side value: {:error, %Mnesia.RecordNotFoundError{id: "undefined", table: BattleSnake.GameForm}}
        (battle_snake) web/channels/game_admin_channel.ex:13: BattleSnake.GameAdminChannel.join/3
        (phoenix) lib/phoenix/channel/server.ex:170: Phoenix.Channel.Server.init/1
        (stdlib) gen_server.erl:328: :gen_server.init_it/6
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by Dkendal** [comment]
fixed in 6620084d6c3524503cd1a86e5b1ab1d19a614b35
