### ISSUE TITLE
Game crash on invalid move

### ISSUE THREAD

**Issue by dlsteuer** [StemboltHQ/battle_snake#9]
It looks like the game ends if it receives an invalid move, here is what is in the logs

```
[error] GenServer {BattleSnake.GameServer.Registry, "887b0f25-3ec1-4f77-affc-717849484bee"} terminating
** (CaseClauseError) no case clause matching: "u"
    (battle_snake) lib/battle_snake/world.ex:72: BattleSnake.World.convert/1
    (battle_snake) lib/battle_snake/world_movement.ex:28: anonymous fn/3 in BattleSnake.WorldMovement.apply/2
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    (battle_snake) lib/battle_snake/world_movement.ex:26: anonymous fn/2 in BattleSnake.WorldMovement.apply/2
    (elixir) lib/map.ex:646: Map.update!/3
    (battle_snake) lib/battle_snake/world.ex:114: BattleSnake.World.step/1
    (elixir) lib/map.ex:646: Map.update!/3
    (battle_snake) lib/battle_snake/game_server/state.ex:119: BattleSnake.GameServer.State.step/1
    (battle_snake) lib/battle_snake/game_server/server.ex:104: BattleSnake.GameServer.Server.handle_info/2
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: :tick
State: %BattleSnake.GameServer.State{delay: 200, game_form: %BattleSnake.GameForm{__meta__: #Ecto.Schema.Metadata<:built, "game">, delay: 200, game_mode: "multiplayer", height: 30, id: "887b0f25-3ec1-4f77-affc-717849484bee", max_food: 5, snakes: [%BattleSnake.SnakeForm{__meta__: #Ecto.Schema.Metadata<:built, "snake">, delete: false, id: nil, url: "http://localhost:9000"}, %BattleSnake.SnakeForm{__meta__: #Ecto.Schema.Metadata<:built, "snake">, delete: false, id: nil, url: "http://localhost:9000"}], width: 30, winners: [], world: %BattleSnake.World{created_at: nil, dead_snakes: [], deaths: [], food: [%BattleSnake.Point{x: 9, y: 8}, %BattleSnake.Point{x: 23, y: 0}, %BattleSnake.Point{x: 16, y: 8}, %BattleSnake.Point{x: 27, y: 23}, %BattleSnake.Point{x: 25, y: 24}], game_form_id: "887b0f25-3ec1-4f77-affc-717849484bee", game_id: "887b0f25-3ec1-4f77-affc-717849484bee", height: 30, id: nil, max_food: 5, moves: %{}, snakes: [%BattleSnake.Snake{color: "#F7931D", coords: [%BattleSnake.Point{x: 1, y: 13}, %BattleSnake.Point{x: 1, y: 13}, %BattleSnake.Point{x: 1, y: 13}], head_url: "http://localhost:9000/swu-logo.png", health: :ok, health_points: 100, id: "9f41ce7c-837e-4baf-8d28-b054609fb9a8", name: "SWU Bounty Snake", taunt: "", url: "http://localhost:9000"}, %BattleSnake.Snake{color: "#F7931D", coords: [%BattleSnake.Point{x: 27, y: 21}, %BattleSnake.Point{x: 27, y: 21}, %BattleSnake.Point{x: 27, y: 21}], head_url: "http://localhost:9000/swu-logo.png", health: :ok, health_points: 100, id: "96d89a25-5929-45db-b953-7f5e7c6858ea", name: "SWU Bounty Snake", taunt: "", url: "http://localhost:9000"}], turn: 0, width: 30}}, game_form_id: "887b0f25-3ec1-4f77-affc-717849484bee", hist: [], objective: #Function<0.31983054/1 in BattleSnake.WinConditions.game_mode/1>, on_change: #Function<7.70356225/1 in BattleSnake.GameForm.to_game_server_state/1>, on_done: #Function<8.70356225/1 in BattleSnake.GameForm.to_game_server_state/1>, on_start: &BattleSnake.GameServer.State.identity/1, status: :cont, winners: [], world: %BattleSnake.World{created_at: nil, dead_snakes: [], deaths: [], food: [%BattleSnake.Point{x: 9, y: 8}, %BattleSnake.Point{x: 23, y: 0}, %BattleSnake.Point{x: 16, y: 8}, %BattleSnake.Point{x: 27, y: 23}, %BattleSnake.Point{x: 25, y: 24}], game_form_id: "887b0f25-3ec1-4f77-affc-717849484bee", game_id: "887b0f25-3ec1-4f77-affc-717849484bee", height: 30, id: nil, max_food: 5, moves: %{}, snakes: [%BattleSnake.Snake{color: "#F7931D", coords: [%BattleSnake.Point{x: 1, y: 13}, %BattleSnake.Point{x: 1, y: 13}, %BattleSnake.Point{x: 1, y: 13}], head_url: "http://localhost:9000/swu-logo.png", health: :ok, health_points: 100, id: "9f41ce7c-837e-4baf-8d28-b054609fb9a8", name: "SWU Bounty Snake", taunt: "", url: "http://localhost:9000"}, %BattleSnake.Snake{color: "#F7931D", coords: [%BattleSnake.Point{x: 27, y: 21}, %BattleSnake.Point{x: 27, y: 21}, %BattleSnake.Point{x: 27, y: 21}], head_url: "http://localhost:9000/swu-logo.png", health: :ok, health_points: 100, id: "96d89a25-5929-45db-b953-7f5e7c6858ea", name: "SWU Bounty Snake", taunt: "", url: "http://localhost:9000"}], turn: 0, width: 30}}
```

**Comment by Dkendal** [comment]
Thanks for the report @dlsteuer ! I'll look into this today.
